# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from login_screen import Ui_LoginWindow

class Ui_startscreen(object):
	def open_login_screen(self):
		self.window2 = QtWidgets.QMainWindow()
		self.ui = Ui_LoginWindow()
		self.ui.setupUi(self.window2)
		self.window2.show()

	def setupUi(self, startscreen):
		startscreen.setObjectName("startscreen")
		startscreen.resize(782, 576)
		startscreen.setStyleSheet("QMainWindow {\n"
"        background-color: \'#8bbdd9\';\n"
"}")
		self.centralwidget = QtWidgets.QWidget(startscreen)
		self.centralwidget.setStyleSheet("QWidget {\n"
"background-color: \'#8bbdd9\';\n"
"}")
		self.centralwidget.setObjectName("centralwidget")
		self.label = QtWidgets.QLabel(self.centralwidget)
		self.label.setGeometry(QtCore.QRect(210, 10, 371, 291))
		self.label.setText("")
		self.label.setPixmap(QtGui.QPixmap("logo2.png"))
		self.label.setScaledContents(True)
		self.label.setObjectName("label")
		self.pushButton = QtWidgets.QPushButton(self.centralwidget)
		self.pushButton.setGeometry(QtCore.QRect(300, 300, 191, 71))
		self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButton.setStyleSheet("QPushButton{\n"
"        border-radius : 30;\n"
"        border: 6px solid \'#0079bf\';\n"
"        border-style: double;\n"
"        font-size: 20px;\n"
"        color: \'white\';\n"
"}")
		self.pushButton.setObjectName("pushButton")
		self.pushButton.clicked.connect(self.open_login_screen)
		self.pushButton.clicked.connect(startscreen.close)
		self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
		self.pushButton_2.setGeometry(QtCore.QRect(300, 390, 191, 71))
		self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButton_2.setMouseTracking(False)
		self.pushButton_2.setStyleSheet("QPushButton{\n"
"        border-radius : 30;\n"
"        border: 6px solid \'#0079bf\';\n"
"        border-style: double;\n"
"        font-size: 20px;\n"
"        color: \'white\';\n"
"\n"
"}")
		self.pushButton_2.setObjectName("pushButton_2")
		startscreen.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(startscreen)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 22))
		self.menubar.setObjectName("menubar")
		startscreen.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(startscreen)
		self.statusbar.setObjectName("statusbar")
		startscreen.setStatusBar(self.statusbar)

		self.retranslateUi(startscreen)
		QtCore.QMetaObject.connectSlotsByName(startscreen)

	def retranslateUi(self, startscreen):
		_translate = QtCore.QCoreApplication.translate
		startscreen.setWindowTitle(_translate("startscreen", "MainWindow"))
		self.pushButton.setText(_translate("startscreen", "Login"))
		self.pushButton_2.setText(_translate("startscreen", "Sign up"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	startscreen = QtWidgets.QMainWindow()
	ui = Ui_startscreen()
	ui.setupUi(startscreen)
	startscreen.show()
	sys.exit(app.exec_())
